### ISSUE TITLE
Problematic tty options

### ISSUE THREAD

**Issue by mariano-dagostino** [xlith/lipsum-cli#1]
Hi. Thanks for sharing this project!

I'm trying to use this together with [rofi](https://github.com/davatorium/rofi/wiki/Script-Launcher) and I found there is a problem when using `lipsum-cli` with pipes.

The docs says:

```
cat start-wars.txt | lipsum-cli
The Empire’s sinister agents, Princess.
```

But if you try to use `lipsum-cli` with xargs 

```
echo "lipsum-cli -w 10" | xargs -i /bin/bash -c "{}"
```

You always get an empty response. I think this is because: `if atty::isnt(Stream::Stdin)` sets the input_source to `stdin`, and there is no `stdin`.

I think a possible solution would be change the precedence described here:

`-t, --text-source <TEXT_SOURCE>    Text source to choose from. Ignored if stdin or -f is used`

So if you specify a `-t` value, it won't read from stdin, and pipes can be used freely.

**Comment by xlith** [comment]
Hello. 
Thanks for the detailed input. I'll have a look at it at the first opportunity.

**Comment by xlith** [comment]
Hey, @mariano-dagostino thanks for the feedback. 

This should fix the issue. Instead of changing the priorities, I added a control to check if the stdin input is not zero length.

Please feel free to open another one if you find anything else.
